### ISSUE TITLE
Is aggregation planned?

### ISSUE THREAD

**Issue by Eldynn** [bafolts/tplant#17]
Hi, is other relation like aggregation planned for the future release?

**Comment by bafolts** [comment]
The aggregation relation could be implemented. The only plan I have right now is to add features as people come up with them. What would the typescript look like for an aggregation relationship? Any member of a type could be an aggregation, that would be easy enough to add.

```
class Car {
    public wheel: Wheel;
}
```

This could then get labeled as an aggregation since `Wheel` would be an aggregate of `Car`.

What did you have in mind?

**Comment by Eldynn** [comment]
Perfect :), maybe make this and further features optionable.
```
class Wheel {
    public size: number;
}
class Car {
    public wheel: Wheel;
}
```
```
@startuml
class Wheel {
    +size: number
}
class Car {
    +wheel: Wheel
}
Car *-- Wheel
@enduml
```

**Comment by marcosvrs** [comment]
Published.
